# Generated by Django 3.0.3 on 2020-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0002_chofer_calif_chofer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chofer', models.IntegerField()),
                ('id_contrato', models.IntegerField()),
                ('direccion', models.CharField(max_length=120)),
                ('barrio', models.CharField(max_length=120)),
                ('destino', models.CharField(max_length=120)),
                ('cant_asientos', models.IntegerField()),
                ('estado', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'contratos',
            },
        ),
    ]
