# Generated by Django 3.0.3 on 2020-03-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0005_auto_20200227_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='email_chofer',
            field=models.CharField(default='eberuruguay@gmail.com', max_length=120),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id_chofer',
            field=models.CharField(max_length=60),
        ),
    ]
