# Generated by Django 3.0.3 on 2020-03-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0006_auto_20200302_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'barrios',
            },
        ),
        migrations.CreateModel(
            name='Chofer_Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chofer', models.IntegerField()),
                ('id_barrio', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'choferes_barrio',
                'unique_together': {('id_chofer', 'id_barrio')},
            },
        ),
    ]
