# Generated by Django 3.0.3 on 2020-03-07 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0007_barrio_chofer_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer_barrio',
            name='id_chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version3.Chofer'),
        ),
    ]
