# Generated by Django 3.0.3 on 2020-03-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0008_auto_20200307_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='id_chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version3.Chofer'),
        ),
    ]
