# Generated by Django 3.0.3 on 2020-03-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0011_colegio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('id_barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version3.Barrio')),
                ('id_colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version3.Colegio')),
            ],
            options={
                'verbose_name_plural': 'tarifas',
            },
        ),
    ]
