# Generated by Django 3.0.3 on 2020-03-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0012_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
