# Generated by Django 3.0.3 on 2020-03-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0013_contrato_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha',
            field=models.IntegerField(default=20200311),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='hora',
            field=models.IntegerField(default=800),
            preserve_default=False,
        ),
    ]
