# Generated by Django 3.0.3 on 2020-03-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0014_auto_20200312_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.CharField(default='2020-03-11', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='hora',
            field=models.CharField(default='07:00', max_length=10),
        ),
    ]
