# Generated by Django 3.0.3 on 2020-03-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0015_auto_20200312_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='ubicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='direccion_colegio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
