# Generated by Django 3.1.7 on 2021-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0016_auto_20200313_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='pass_chofer',
            field=models.CharField(default='1234', max_length=16),
        ),
    ]
