# Generated by Django 3.1.7 on 2021-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version3', '0017_chofer_pass_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='telefono',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
